d3/4.0.0

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -28,13 +28,14 @@ D3_DEFAULT_CONFIG=kernel/d3/d3_defconfig
 linux_ZIMAGE=@LINUX_BUILD_PATH@/arch/arm64/boot/zImage
 linux_IMAGE=@LINUX_BUILD_PATH@/arch/arm64/boot/Image
 linux_SIGNED_IMAGE=@DEPLOY_BUILD_PATH@/boot/boot_sigheader.img.encrypt
-LINUX_PACKAGE_FILE=kernel/linux-image-4.9.140+@D3_JETSON_BSP_VERSION@-@CUSTOMER@+_1_arm64.deb
+LINUX_PACKAGE_FILE=linux-image-4.9.140+@D3_JETSON_BSP_VERSION@-@CUSTOMER@+_1_arm64.deb
 BIN_RELEASE_DIR=d3-jetson-bsp-bin-@VERSION_NAME@
 BIN_RELEASE_FILE=@DEPLOY_BUILD_PATH@/d3-jetson-bsp-bin-@VERSION_NAME@.tar.gz
 SRC_RELEASE_FILE=@DEPLOY_BUILD_PATH@/d3-jetson-bsp-src-@VERSION_NAME@.tar.gz
 ZIP_RELEASE_FILE=artifacts/d3-jetson-bsp-@VERSION_NAME@.zip
 ZIP_RELEASE_STAGING_DIR=d3-jetson-bsp-@VERSION_NAME@
 RELNOTES_PDF_FILE=doc/D3-Jetson-BSP-Release-Notes.pdf
+NXCBUP_PDF_FILE=doc/D3-Jetson-NX-Carrier-Bringup.pdf
 RSYNC_OPTS=-ar --exclude=.git --no-owner --no-group $(if $V,--progress)
 # Filename of the deb for d3-jetson-util.  Cannot be changed
 UTIL_PACKAGE_FILE=d3-jetson-util_@VERSION_NAME@-1_arm64.deb
@@ -55,8 +56,13 @@ if XAVIER
 FLASH_CHIP_ID=0x19
 SYNC_TARGETS=sync-modules sync-boot sync-logo sync-nvlibs sync-debug sync-dtb sync-kernel
 else
+if NX
+FLASH_CHIP_ID=0x19
+SYNC_TARGETS=sync-modules sync-boot sync-logo sync-nvlibs sync-debug sync-dtb
+else
 FLASH_CHIP_ID=0x18
 SYNC_TARGETS=sync-modules sync-boot sync-logo sync-nvlibs sync-debug sync-dtb
+endif
 endif
 
 
@@ -68,13 +74,14 @@ endif
 # Leading spaces required to hide this from automake --- see
 # https://patchwork.kernel.org/patch/6709921/
 #
+# As of Automake 1.15.1, $(eval) required to hide assignment from automake.
+#
 # Can't use make's ?= because it maps to =, not :=.
  ifeq ($(origin D3_JETSON_BSP_BUILDID), undefined)
- D3_JETSON_BSP_BUILDID := $(shell uuidgen -r)
+ $(eval D3_JETSON_BSP_BUILDID := $(shell uuidgen -r))
+ $(warning ---------------- Build ID is $(D3_JETSON_BSP_BUILDID))
  endif
 export D3_JETSON_BSP_BUILDID
-
-$(warning ---------------- Build ID is $(D3_JETSON_BSP_BUILDID))
 
 D3_IMX390_HDR_ENABLE := $(shell if [ $$(@KERNEL_DIR@/scripts/config --file $(LINUX_BUILD_PATH)/.config -s d3_imx390_hdr_enable) == 'y' ]; then echo 1; else echo 0; fi)
 D3_OV10640_HDR_ENABLE := $(shell if [ $$(@KERNEL_DIR@/scripts/config --file $(LINUX_BUILD_PATH)/.config -s d3_ov10640_hdr_enable) == 'y' ]; then echo 1; else echo 0; fi)
@@ -83,16 +90,17 @@ D3_OV10640_HDR_ENABLE := $(shell if [ $$(@KERNEL_DIR@/scripts/config --file $(LI
 export D3_DTCCPP_FLAGS=-DD3_JETSON_BSP_BUILDID='"$(D3_JETSON_BSP_BUILDID)"' -DD3_IMX390_HDR_ENABLE=$(D3_IMX390_HDR_ENABLE) -DD3_OV10640_HDR_ENABLE=$(D3_OV10640_HDR_ENABLE)
 
 # Make all of the directories we need exist.
-$(shell  mkdir -p "$(BIN_RELEASE_DIR)/doc" "$(BIN_RELEASE_DIR)/dtb" "@DEPLOY_BUILD_PATH@" "@LINUX_BUILD_PATH@" "@DEPLOY_BUILD_PATH@/boot" artifacts)
-
+$(shell  mkdir -p "$(BIN_RELEASE_DIR)/doc" "$(BIN_RELEASE_DIR)/dtb" "@DEPLOY_BUILD_PATH@" "@LINUX_BUILD_PATH@" "@DEPLOY_BUILD_PATH@/boot" @ARTIFACT_PATH@ "@TOP_BUILD_PATH@/$(ZIP_RELEASE_STAGING_DIR)")
 
 .PHONY: linux-defconfig linux-dtbs linux-clean
 .PHONY: reboot shutdown
 .PHONY: deploy deploy-clean flash-dtb
 .PHONY: sync sync-boot sync-modules sync-debug sync-dtb
-.PHONY: release release-src release-bin release-zip bin-kernel doc
+.PHONY: release release-src release-bin release-zip doc
 .PHONY: sign-dtb
 .PHONY: show-config clean-local
+.PHONY: show-config clean-local l4t-dir
+.PHONY: kernel-bindeb-pkg
 
 # distribution files: listed as phony so we don't have to
 # expressly track their prerequisites.
@@ -106,7 +114,7 @@ define HELP_TEXT
 	deploy          - builds kernel and DTB
 	deploy-clean    - deletes build artifacts in the deployment tree
 	sync            - rsyncs kernel, kernel modules, and dtb to target
-	sync-debug      - rsyncs debug/ to target
+	sync-debug      - rsyncs scripts/target/ to target
 	sync-kernel     - (Xavier only) copies signed kernel image to device and writes it to the kernel partition
 	sync-modules    - rsyncs kernel modules to target
 	sync-nvlibs     - copies nvidia libraries that have been modified from release to target
@@ -118,7 +126,7 @@ define HELP_TEXT
 	linux-menuconfig- launches curses based kernel config editor
 	linux-dtbs      - builds dtbs
 	linux-dtbs-install- installs dtbs
-	linux-clean     - deletes build artifacts in the kernel tree
+	linux-clean	- deletes build artifacts in the kernel tree
 	reboot          - reboots target
 	shutdown        - halts target
 	sign-dtb        - signs dtb file with L4T
@@ -126,10 +134,11 @@ define HELP_TEXT
 	release         - creates a release (binary and source)
 	release-src     - prepares a source release tarball
 	release-bin     - builds a binary release
+	kernel-deb-clean- cleans up an in-tree build
 	release-zip     - build a ZIP file of a release
-	bin-kernel      - creates kernel .deb package
 	doc             - builds documentation (requires pandoc and latex)
 	show-config     - show the configuration supplied to configure
+	l4t-dir         - print the L4T directory
 endef
 export HELP_TEXT
 help:
@@ -148,35 +157,28 @@ doc:
 $(UTIL_PACKAGE_FILE):
 	$(AM_V_GEN)
 	$(v)( cd d3-jetson-util; CC=true dpkg-buildpackage -b -us -uc -a arm64 \
-			-t aarch64-linux-gnu > /dev/null )
+			-t aarch64-linux-gnu $(suppress_unless_v) )
 	$(v)cp $(UTIL_PACKAGE_FILE) "$(BIN_RELEASE_DIR)"
 d3-jetson-util: $(UTIL_PACKAGE_FILE)
 
 
-$(BIN_RELEASE_FILE): bin-kernel doc d3-jetson-util
+$(BIN_RELEASE_FILE): kernel-bindeb-pkg doc d3-jetson-util
 	$(AM_V_GEN)
 	$(vecho) "ID      $(D3_JETSON_BSP_BUILDID)"
 	$(vecho) "CP      PDFs"
 	$(v)cp "$(RELNOTES_PDF_FILE)" "$(BIN_RELEASE_DIR)"/doc/
+	$(v)cp "$(NXCBUP_PDF_FILE)" "$(BIN_RELEASE_DIR)"/doc/
 	$(vecho) "CP      DTBs"
-	$(v)find kernel/kernel-4.9/arch/arm64 -type f -name '*.dtb' -exec cp {} "$(BIN_RELEASE_DIR)"/dtb/ ';'
-	$(vecho) "CP      SIGNED DTBs"
-	$(v)find kernel/kernel-4.9/arch/arm64 -type f -name '*_sigheader.dtb.encrypt' -exec cp {} "$(BIN_RELEASE_DIR)"/dtb/ ';'
+	$(v)find @LINUX_BUILD_PATH@/arch/ -type f | grep -P '^((?!\/tegra[^\/]*).)*.dtb$$' | xargs -I @ cp '@' "$(BIN_RELEASE_DIR)"/dtb/
 	$(vecho) "CP      kernel package"
-	$(v)cp "./l4t-submodules/$(LINUX_PACKAGE_FILE)" "$(BIN_RELEASE_DIR)"
+	$(v)cp "@TOP_BUILD_PATH@/$(LINUX_PACKAGE_FILE)" "$(BIN_RELEASE_DIR)"/
 	$(vecho) "GEN     $(HASH_FILE)"
 	$(v)find "$(BIN_RELEASE_DIR)" -type f -exec sha1sum {} ';' >> "$(HASH_FILE)"
 	$(v)mv "$(HASH_FILE)" "$(BIN_RELEASE_DIR)"
 	$(vecho) "TGZ     $(BIN_RELEASE_DIR)"
 	$(v)tar czf "$(BIN_RELEASE_FILE)" "$(BIN_RELEASE_DIR)"
+	$(vecho) '[$@] complete'
 release-bin: $(BIN_RELEASE_FILE)
-
-
-$(LINUX_PACKAGE_FILE): bin/kernel-deb
-	$(AM_V_GEN)
-	$(v)bin/kernel-deb @CUSTOMER@ '@D3_JETSON_BSP_VERSION@'
-	$(v)cp "./l4t-submodules/$(LINUX_PACKAGE_FILE)" "@DEPLOY_BUILD_PATH@/"
-bin-kernel: $(LINUX_PACKAGE_FILE)
 
 
 $(SRC_RELEASE_FILE):
@@ -187,18 +189,34 @@ $(SRC_RELEASE_FILE):
 	--prefix d3-jetson-bsp-src-@VERSION_NAME@/ \
 	--tree-ish $(GIT_BRANCH) \
 	$(SRC_RELEASE_FILE)
+	$(vecho) '[$@] complete'
 release-src: $(SRC_RELEASE_FILE)
 
 
+# Release: build binary and source packages.
 release: release-bin release-src
 
-release-zip: release
-	$(vecho) "ZIP     $(ZIP_RELEASE_FILE)"
-	$(v)zip -j "$(ZIP_RELEASE_FILE)" \
-		"$(BIN_RELEASE_FILE)" "$(SRC_RELEASE_FILE)" \
-		"$(RELNOTES_PDF_FILE)"
 
-clean-local: linux-clean deploy-clean
+$(ZIP_RELEASE_FILE): release
+	$(AM_V_GEN)
+	$(v)mkdir -p '@TOP_BUILD_PATH@/$(ZIP_RELEASE_STAGING_DIR)'
+	$(v)bash -c 'cd "@TOP_BUILD_PATH@/$(ZIP_RELEASE_STAGING_DIR)" ; \
+		for f in "@ARTIFACT_PATH@"/* ; do \
+			ln -s -f "$$(realpath "$$f")" "$${f##*/}" ; \
+		done'
+	$(v)zip -j "$(ZIP_RELEASE_FILE)" "$(BIN_RELEASE_FILE)" "$(SRC_RELEASE_FILE)" \
+		"$(RELNOTES_PDF_FILE)" "$(NXCBUP_PDF_FILE)"
+	@: #XXX cleanup $(v)rm -rf '$(ZIP_RELEASE_STAGING_DIR)'
+	$(vecho) '[$@] complete'
+release-zip: $(ZIP_RELEASE_FILE)
+
+
+# automake automatically adds 'clean: clean-local'
+clean-local: linux-clean deploy-clean kernel-deb-clean
+
+
+kernel-deb-clean:
+	$(v)bin/kernel-deb-clean
 
 
 # Probably need different config based on target type.
@@ -219,8 +237,7 @@ linux-menuconfig:
 
 
 linux-clean:
-	$(vecho) "RM     @LINUX_BUILD_PATH@"
-	$(v)rm -Rf "@LINUX_BUILD_PATH@"
+	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) @LINUX_ARGS@ clean
 
 
 # Just compile the kernel.  Provided for use by Makefiles in /mk .
@@ -229,15 +246,60 @@ _compile_kernel:
 		$(if ${COMPILE_KERNEL_ARGS}, ${COMPILE_KERNEL_ARGS}, \
 		CFLAGS_build-id.o=-DD3_JETSON_BSP_BUILDID='\"$(D3_JETSON_BSP_BUILDID)\"' zImage Image modules dtbs)
 
-# Default target
-deploy:
-	touch kernel/d3/drivers/d3/build-id/build-id.c
-	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) _compile_kernel
-	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) @LINUX_ARGS@ modules_install headers_install
+
+$(LINUX_BUILD_CONFIG): $(D3_BUILD_CONFIG)
+	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) @LINUX_ARGS@ d3_defconfig \
+		$(if ${MIK_ARGS}, ${MIK_ARGS}, CFLAGS_build-id.o=-DD3_JETSON_BSP_BUILDID='\"$(D3_JETSON_BSP_BUILDID)\"') \
+		$(if ${MIK_TGT}, ${MIK_TGT}, zImage Image modules dtbs)
+
+
+# Make a kernel package (and build the kernel if necessary).  The package name
+# includes the kernel version, BSP version, and customer.
+# Leaves the result in build/.
+# TODO refactor to remove the dependency on deploy - some files are being
+# compiled twice, as far as I can tell.
+kernel-bindeb-pkg: deploy
+	$(v)rm -f "@TOP_BUILD_PATH@"/*.deb "@TOP_BUILD_PATH@"/*.changes
+	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) @LINUX_ARGS@ \
+		CFLAGS_build-id.o=-DD3_JETSON_BSP_BUILDID='\"$(D3_JETSON_BSP_BUILDID)\"' \
+		L4TDIR="@L4TDIR@" \
+		KBUILD_PKG_ROOTCMD='fakeroot' \
+		BUILDDEB_NO_DEBUG_PACKAGE=y \
+		LOCALVERSION="+@D3_JETSON_BSP_VERSION@-@CUSTOMER@+" KDEB_PKGVERSION="1"\
+		BUILDDEB_PREPKG_HOOK="$$(realpath -qm bin/builddeb-hook)" \
+		bindeb-pkg
+	$(vecho) '[$@] complete'
+
+
+# Populate build/deploy - internal target.  Don't need to install SIGNED_DTB
+# since it's already in @DEPLOY_BUILD_PATH@.
+_populate_deploy:
 	$(v)install -D "$(linux_ZIMAGE)" "@DEPLOY_BUILD_PATH@/boot/"
 	$(v)install -D "$(linux_IMAGE)" "@DEPLOY_BUILD_PATH@/boot/"
 	$(v)install -D @LINUX_BUILD_PATH@/arch/arm64/boot/dts/*.dtb "@DEPLOY_BUILD_PATH@/boot/"
-	$(v)echo "Done - build ID $(D3_JETSON_BSP_BUILDID)"
+	@# Make sure the D3 drivers actually made it into the compiled kernel.
+	@# Use the build-id driver as a proxy for all our drivers.
+	$(v)grep buildid_check_dtb_match "@LINUX_BUILD_PATH@/System.map" $(suppress_unless_v) \
+		|| { echo "*** Error: D3 drivers were not compiled into the kernel - check Kconfig" ; false ; }
+
+
+# Default target
+deploy: $(LINUX_BUILD_CONFIG)
+	@# Every build gets a new build ID
+	$(v)touch kernel/d3/drivers/d3/build-id/build-id.c
+	@# Remove the "command" lines from ISP files.  Aborts the build
+	@# if any changes were made.
+	$(v)if ! perl -i -ne 'BEGIN { exit(0) unless @ARGV } /^#\s+command\b/ and $$code=1 or print; END { exit !!$$code }' `find d3-jetson-util kernel/d3 -name '*.isp'` ; then \
+		echo '*** Warning: removed command lines from some ISP files.  Please commit changes and re-run.' ; \
+		exit 1 ; \
+	fi
+	@# Build!
+	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) _compile_kernel
+	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) sign-dtb
+	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) @LINUX_ARGS@ modules_install headers_install firmware_install
+	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) _populate_deploy
+	$(vecho) '[$@] complete - build ID $(D3_JETSON_BSP_BUILDID)'
+
 
 deploy-clean:
 	$(vecho) "RM     @DEPLOY_BUILD_PATH@"
@@ -246,41 +308,41 @@ deploy-clean:
 
 reboot:
 	$(vecho) "REBOOT   @TARGET_HOST@"
-	$(v)ssh @TARGET_HOST@ sudo shutdown -r now& exit || true
+	$(v)ssh @USERNAME_SSH@ @TARGET_HOST@ sudo shutdown -r now& exit || true
 
 
 shutdown:
 	$(vecho) "HALT     @TARGET_HOST@"
-	$(v)ssh @TARGET_HOST@ sudo shutdown -P now& exit || true
+	$(v)ssh @USERNAME_SSH@ @TARGET_HOST@ sudo shutdown -P now& exit || true
 
 
 sync-debug:
-	$(vecho) "SYNC     debug/"
-	$(v)rsync debug/ @TARGET_HOST@:debug/ $(RSYNC_OPTS)
+	$(vecho) "SYNC     scripts/target/"
+	$(v)rsync scripts/target/ @USERNAME_AT@@TARGET_HOST@:debug/ $(RSYNC_OPTS)
 
 
 sync-boot:
 	$(vecho) "SYNC     boot/"
-	$(v)rsync @DEPLOY_BUILD_PATH@/boot/ $(TARGET_HOST):/boot/ $(RSYNC_OPTS)
+	$(v)rsync @DEPLOY_BUILD_PATH@/boot/ @USERNAME_AT@@TARGET_HOST@:/boot/ $(RSYNC_OPTS)
 
 sync-modules:
 	$(vecho) "SYNC     lib/modules/"
 	$(v)for d in @DEPLOY_BUILD_PATH@/lib/modules/*; do \
 		[ "$(V)" ] && echo "         $${d}"; \
-		rsync $${d}/ @TARGET_HOST@:/lib/modules/$$(basename $${d}) \
+		rsync $${d}/ @USERNAME_AT@@TARGET_HOST@:/lib/modules/$$(basename $${d}) \
 			$(RSYNC_OPTS) $(if ${RSYNC_NO_DELETE},,--delete); \
 	done
-	$(v)ssh @TARGET_HOST@ sync
+	$(v)ssh @USERNAME_SSH@ @TARGET_HOST@ sync
 
 sync-nvlibs:
 	$(vecho) "SYNC     $(NVLIBS_PATH)"
-	$(v) if [ -e $(NVLIBS_PATH) ]; then scp $(NVLIBS_PATH)/* $(TARGET_HOST):$(TARGET_NVLIBS_PATH); fi
-	$(v)ssh @TARGET_HOST@ sync
+	$(v)if [ -e "$(NVLIBS_PATH)" ]; then scp @USERNAME_SCP@ "$(NVLIBS_PATH)"/* $(TARGET_HOST):"$(TARGET_NVLIBS_PATH)"; fi
+	$(v)ssh @USERNAME_SSH@ @TARGET_HOST@ sync
 
 sync-logo: $(BOOT_LOGO_FILE)
-	$(vecho) "SYNC     $(BOOT_LOGO_FILE)"
-	$(v)scp $(BOOT_LOGO_FILE) $(TARGET_HOST):debug/boot-logo.blob
-	$(v)ssh @TARGET_HOST@ 'sudo dd if=debug/boot-logo.blob of=/dev/disk/by-partlabel/BMP && sync'
+	$(vecho) "SYNC     $<"
+	$(v)scp @USERNAME_SCP@ $< $(TARGET_HOST):debug/boot-logo.blob
+	$(v)ssh @USERNAME_SSH@ @TARGET_HOST@ 'sudo dd if=debug/boot-logo.blob of=/dev/disk/by-partlabel/BMP && sync' $(suppress_unless_v)
 
 sync: $(SYNC_TARGETS)
 	$(v)echo "Run 'make reboot' when ready"
@@ -290,61 +352,85 @@ sync: $(SYNC_TARGETS)
 	$(v)+$(KCONFIG_ASSIGNMENT) $(MAKE) @LINUX_ARGS@ dtbs
 
 $(DEPLOY_BUILD_PATH)/boot/%_sigheader.dtb.encrypt: $(DTB_BUILD_PATH)/%.dtb
-	$(vecho) "SIGN      $^"
+	$(vecho) "SIGN      $<"
+	@: # Check for existence of unsigned DTB.  Prints if not found.
+	$(v)stat "$<" >/dev/null
 	$(v)cd $(DEPLOY_BUILD_PATH)/boot; \
 		@L4TDIR@/bootloader/tegraflash.py --chip $(FLASH_CHIP_ID) \
-		--cmd "sign $^" --skipuid;
+		--cmd "sign $<" --skipuid $(suppress_unless_v)
 
 sign-dtb: $(SIGNED_DTB)
 
-sync-dtb: sign-dtb
-	$(vecho) "SYNC     $(SIGNED_DTB)"
-	$(v)scp $(SIGNED_DTB) @TARGET_HOST@:~/device_tree.dtb.encrypt
-	$(v)ssh @TARGET_HOST@ sudo dd if=device_tree.dtb.encrypt of=/dev/disk/by-partlabel/kernel-dtb
+sync-dtb: $(SIGNED_DTB)
+	$(vecho) "SYNC     $<"
+	$(v)scp @USERNAME_SCP@ "$<" @TARGET_HOST@:~/device_tree.dtb.encrypt
+	$(v)ssh @USERNAME_SSH@ @TARGET_HOST@ sudo dd if=device_tree.dtb.encrypt of=/dev/disk/by-partlabel/kernel-dtb
 
 if XAVIER
-sign-kernel:
+
+
+# TODO: use the flash.sh configuration files to get $INITRD_IN_BOOTIMG
+# and $INITRD, and use them in the below.  (See flash.sh output with set -x)
+$(linux_SIGNED_IMAGE): $(linux_IMAGE)
 	$(vecho) "SIGN     $(linux_IMAGE)"
 	$(v)cd @L4TDIR@/bootloader; \
-		./mkbootimg --kernel $(linux_IMAGE) --ramdisk initrd --board mmcblk0p1 --output $(DEPLOY_BUILD_PATH)/boot/boot.img;
+		./mkbootimg --kernel $(linux_IMAGE) --ramdisk l4t_initrd.img --board mmcblk0p1 --output $(DEPLOY_BUILD_PATH)/boot/boot.img;
 	$(v)cd $(DEPLOY_BUILD_PATH)/boot; \
 		@L4TDIR@/bootloader/tegraflash.py --chip $(FLASH_CHIP_ID) \
-		--cmd "sign boot.img" --skipuid > /dev/null;
+		--cmd "sign boot.img" --skipuid $(suppress_unless_v) ;
 
-sync-kernel: sign-kernel
+sign-kernel: $(linux_SIGNED_IMAGE)
+
+sync-kernel: $(linux_SIGNED_IMAGE)
 	$(vecho) "SYNC     $(linux_SIGNED_IMAGE)"
-	$(v)scp $(linux_SIGNED_IMAGE) @TARGET_HOST@:~/boot.img.encrypt > /dev/null
-	$(v)ssh @TARGET_HOST@ sudo dd bs=10MB if=boot.img.encrypt of=/dev/disk/by-partlabel/kernel > /dev/null 2>&1
+	$(v)scp @USERNAME_SCP@ $(linux_SIGNED_IMAGE) @TARGET_HOST@:~/boot.img.encrypt $(suppress_unless_v)
+	$(v)ssh @USERNAME_SSH@ @TARGET_HOST@ sudo dd bs=10MB if=boot.img.encrypt of=/dev/disk/by-partlabel/kernel $(suppress_unless_v)
+	$(vecho) "REBOOT"
+	$(v)ssh @TARGET_HOST@ sudo reboot now $(suppress_unless_v)
+
 # On Tx2 the kernel is loaded from /boot on the rootfs.
 # On Xavier (only) the kernel is written to a raw partition.
 flash-kernel:
 	$(vecho) "FLASH     $(linux_IMAGE)"
-	$(v)(cd "@L4TDIR@"; sudo ./flash.sh -k kernel -K "$(linux_IMAGE)" jetson-@SYSTEM_TYPE@ mmcblk0p1 > /dev/null; )
+	$(v)(cd "@L4TDIR@"; sudo ./flash.sh -k kernel -K "$(linux_IMAGE)" jetson-@SYSTEM_TYPE@ mmcblk0p1 $(suppress_unless_v) ; )
+
 #On Tx2, the kernel cmdline is loaded from extlinux.conf
 #On Xavier, kernel cmdline is baked into the device tree by flash.sh
 flash-dtb:
 	$(vecho) "XAVIER FLASH     @DTB_FILE@"
 	$(vecho) "CMDLINE          $${XAVIER_K_CMDLINE}"
-	$(v)(cd "@L4TDIR@"; sudo ./flash.sh -k kernel -C "$${XAVIER_K_CMDLINE}" -k kernel-dtb -d "@DTB_FILE@" jetson-@SYSTEM_TYPE@ mmcblk0p1 > /dev/null; )
-else
+	$(v)(cd "@L4TDIR@"; sudo ./flash.sh -k kernel -C "$${XAVIER_K_CMDLINE}" -k kernel-dtb -d "@DTB_FILE@" jetson-@SYSTEM_TYPE@ mmcblk0p1 $(suppress_unless_v) ; )
+
+else # not XAVIER
+
 flash-dtb:
 	$(vecho) "FLASH     @DTB_FILE@"
-	$(v)(cd "@L4TDIR@"; sudo ./flash.sh -k kernel-dtb -d "@DTB_FILE@" jetson-@SYSTEM_TYPE@ mmcblk0p1 > /dev/null; )
+	$(v)(cd "@L4TDIR@"; sudo ./flash.sh -k kernel-dtb -d "@DTB_FILE@" jetson-@SYSTEM_TYPE@ mmcblk0p1 $(suppress_unless_v) ; )
 endif
 
 
 show-config:
-	$(vecho) "     -D3 Configuration-"
-	$(vecho) "Version          : @VERSION_NAME@"
-	$(vecho) "System Type      : @SYSTEM_TYPE@"
-	$(vecho) "Target Host      : @TARGET_HOST@"
-	$(vecho) "Kernel config    : $(if @KCONFIG_FILE@,@KCONFIG_FILE@,<default>)"
-	$(vecho) "DTB File         : @DTB_FILE@"
-	$(vecho) "L4T Directory    : @L4TDIR@"
-	$(v) ( id="$$(strings build/kernel/drivers/d3/build-id/build-id.o 2>/dev/null \
+	-$(vecho) "     -D3 Configuration-"
+	-$(vecho) "Version          : @VERSION_NAME@"
+	-$(vecho) "System Type      : @SYSTEM_TYPE@"
+	-$(vecho) "Target Host      : @TARGET_HOST@"
+	-$(vecho) "Kernel config    : $(if @KCONFIG_FILE@,@KCONFIG_FILE@,<default>)"
+	-$(vecho) "DTB File         : @DTB_FILE@"
+	-$(vecho) "L4T Directory    : @L4TDIR@"
+	-$(v) ( id="$$(strings build/kernel/drivers/d3/build-id/build-id.o 2>/dev/null \
 			| grep -Ei '^([0-9a-f]{4,8}-){4}[0-9a-f]{12}' 2>/dev/null)" && \
 		echo "   Build ID of most recent build: $${id}" ) ; \
 		true
+	-$(vecho)
+	-$(vecho) 'To recreate this configuration, run:'
+	-$(vecho) '  ./configure --with-system-type="@SYSTEM_TYPE@" ' \
+		'--with-target-host="@TARGET_HOST@" ' \
+		$(if @KCONFIG_FILE@,'--with-kconfig="@KCONFIG_FILE@" ',) \
+		'--with-dtb="@DTB_FILE@" ' \
+		'--with-l4t="@L4TDIR@" '
+
+l4t-dir:
+	@echo @L4TDIR@
 
 # Set the main target - automake automatically adds 'all: all-local'
 all-local: deploy
diff --git a/bin/jenkins-build b/bin/jenkins-build
--- a/bin/jenkins-build
+++ b/bin/jenkins-build
@@ -3,7 +3,6 @@
 # for that below.
 
 echo "Started building at $(date) on $(hostname)"
-    # Compare to job-start time to see how long the clone took
 set -o errexit
 set -o pipefail
 
@@ -23,9 +22,6 @@ function branch_info() {
 }
 
 ###########################################
-
-# Leave this turned on!  It makes debugging much easier.
-set -x
 
 # Is the repo dirty?
 if git status --porcelain=v2 | grep -q . ; then
@@ -51,17 +47,17 @@ elif [[ "$jenkins" ]]; then
     # If no command options, default to using remote branch mode
     fresh_in_place=
     case $1 in
-        # Build using the commit Jenkins checked out
-        --fresh-in-place)
-            fresh_in_place=1
-            # Needed for git-archive-all.sh
-            export GIT_BRANCH=$GIT_COMMIT
-            ;;
+	# Build using the commit Jenkins checked out
+    	--fresh-in-place) 
+	    fresh_in_place=1
+	    # Needed for git-archive-all.sh
+	    export GIT_BRANCH=$GIT_COMMIT
+	    ;;
 
-        # Build using the remote branch specified by user in Jenkins
-        *)
-            export GIT_BRANCH="$(echo "$1" | sed -E 's/^[^\/]+\///')"
-            ;;
+	# Build using the remote branch specified by user in Jenkins
+	*)
+    	    export GIT_BRANCH="$(echo "$1" | sed -E 's/^[^\/]+\///')"
+	    ;;
     esac
 
 elif [[ -z "$jenkins" && "$1" ]]; then
@@ -89,8 +85,8 @@ if [[ -z "$fresh_in_place" ]]; then
     fi
 
     if [[ -z "$upstream_remote" ]]; then
-        echo "Could not find upstream remote for branch $GIT_BRANCH" 1>&2
-        exit 1
+    	echo "Could not find upstream remote for branch $GIT_BRANCH" 1>&2
+    	exit 1
     fi
 
     upstream_url="$(git remote get-url "$upstream_remote")"
@@ -105,17 +101,16 @@ fi
 if [[ "$jenkins" ]]; then
     # If build was triggered manually, clear out the initial clone that Jenkins did...
     if [[ -z "$fresh_in_place" ]]; then
-        time find . -mindepth 1 -maxdepth 1 -exec rm -rf {} +
-
-        # ... and replace it with a shallow clone of everything.
-        echo "Cloning recursively from $upstream_remote at $upstream_url"
-        time git clone -v "$upstream_url" '.' \
+	time find . -mindepth 1 -maxdepth 1 -exec rm -rf {} +
+    	# ... and replace it with a shallow clone of everything.
+    	echo "Cloning recursively from $upstream_remote at $upstream_url"
+    	time git clone -v "$upstream_url" '.' \
             --recurse-submodules --shallow-submodules --depth 1 --single-branch \
             --branch "$GIT_BRANCH"
     elif [[ "$fresh_in_place" ]]; then
-        # If build was triggered by Gerrit, update submodules with depth=1
-        echo "Updating submodules"
-        git submodule update --init --recursive --depth 1
+	# If build was triggered by Gerrit, update submodules with depth=1
+	echo "Updating submodules"
+	git submodule update --init --recursive --depth 1
     fi
 else
     # Update submodules, just in case it hasn't been done
@@ -138,12 +133,15 @@ fi
 # Generate the configure script from configure.ac
 ./bootstrap
 CONFIG_SHELL=/bin/bash /bin/bash ./configure \
-    --with-l4t=/opt/nvidia/JetPack_4.3_Linux_P2888/Linux_for_Tegra
+    --with-l4t=/opt/nvidia/JetPack_4.2.2_Linux_GA_P2888/Linux_for_Tegra
 
-# Pull in our kernel configuration.
-make linux-defconfig
+# Assumes arm64, which Jetson always is ;) .
+ARCH=arm64 make linux-defconfig
 
 # Build all the things in all the land.
-make release-zip
+#make --debug=bj release-zip     # for debugging
 
+# Normal build
+export CONCURRENCY_LEVEL="$(grep -c '^processor' /proc/cpuinfo)"
+make -j"$CONCURRENCY_LEVEL" release-zip
 echo "Finished building at $(date)"
diff --git a/d3-jetson-util/scripts/d3-install-dtb b/d3-jetson-util/scripts/d3-install-dtb
--- a/d3-jetson-util/scripts/d3-install-dtb
+++ b/d3-jetson-util/scripts/d3-install-dtb
@@ -15,17 +15,25 @@
 # FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 # more details.
 
+set -o errexit
+set -o pipefail
+shopt -s extglob
+
 [[ -t 0 && -t 1 ]] || { echo "Can't run - not on a terminal" ; exit ; }
 
-shopt -s extglob
-ME="\e[34m[d3-install-dtb]\e[39m"
+function pr() {
+    echo -ne "\e[34m[d3-install-dtb]\e[39m "
+    printf "%s" "$@"
+    echo
+}
+
 ROOT_DTB_DIR="/usr/lib"
 cd $ROOT_DTB_DIR
 
-echo -e "$ME Choose an installed D3 BSP release"
+pr "Choose an installed D3 BSP release"
 select LIMAGE in ./linux-image*; do
     test -n "$LIMAGE" && break
-    echo "$ME Select a valid d3 bsp kernel release"
+    pr "Select a valid d3 bsp kernel release"
 done
 
 DTB_DIR="$ROOT_DTB_DIR/$LIMAGE"
@@ -38,20 +46,30 @@ declare -a DTB_ARR
 
 # Text between 'DESC' markers is the names of the products that each
 # DTB corresponds to
-for file in ./!(tegra*)+(.dtb.encrypt); do
+shopt -s nullglob
+files=(./!(tegra*)+(.dtb.encrypt))
+shopt -u nullglob
+
+if [[ "${#files[@]}" -lt 1 ]]; then
+    echo "No DTB files found in $DTB_DIR" 1>&2
+    exit 1
+fi
+
+for file in "${files[@]}" ; do
     DTB_ARR_RAW+=("$file")
     DTB_ARR+=("$(strings < "$file" | grep -P 'DESC<[^>]+>DESC' \
-	| sed 's/[>]*DESC[<]*//g')")
+       | sed 's/[>]*DESC[<]*//g') ($(sed -E 's/^\.\/|\.encrypt$|_sigheader//g' <<<"$file"))")
 done
 
-echo "Choose a dtb to install"
+pr "Choose a dtb to install"
 select DTB in "${DTB_ARR[@]}"; do
     test -n "$DTB" && break
-    echo "$ME Select a valid signed dtb"
+    pr "Select a valid signed dtb"
 done
 
-if sudo dd if="${DTB_ARR_RAW[$REPLY-1]}" of="/dev/disk/by-partlabel/kernel-dtb"; then
-    echo -e "[d3-install-dtb] \e[32mkernel-dtb has been flashed!\e[39m"
+selected="${DTB_ARR_RAW[$REPLY-1]}"
+if sudo dd if="$selected" of="/dev/disk/by-partlabel/kernel-dtb"; then
+    echo -e "[d3-install-dtb] \e[32mkernel-dtb has been flashed! (file $selected)\e[39m"
 else
-    echo -e "$ME \e[31mdd has failed to write dtb!\e[39m"
+    echo -e "[d3-install-dtb] \e[31mdd has failed to write dtb!\e[39m"
 fi
